# version: "3"
services:
  api:
    build: .
    ports:
      - 8000:8000
    volumes:
      - ./:/usr/src/app
    # env_file:
    #     - ./.env
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXP_MINUTES=${ACCESS_TOKEN_EXP_MINUTES}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - SUPABASE_BUCKET=${SUPABASE_BUCKET}
      - PLAYTOMIC_API_URL=${PLAYTOMIC_API_URL}
      - PLAYTOMIC_EMAIL=${PLAYTOMIC_EMAIL}
      - PLAYTOMIC_PASSWORD=${PLAYTOMIC_PASSWORD}
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=padeltour
    volumes:
      - padeltour_postgres-db:/var/lib/postgresql/data  # Use your existing named volume

volumes:
  padeltour_postgres-db:
    # external: true  # Indicate that this volume already exists